vehicle_model:
  name: "GreenMengShi193"
  manufacturer: "jojo"
  model: "GreenMengShi193"

sensors:
  lidar:
    num: 1
    lidar_1:
      config_file: "rslidar.yaml"
      calibration_file: "calib/rslidar.ini"

  camera:
    compress_ratio: 50
    num: 7
    camera_1:
      resize: [1920, 1080]
      config_file: "camera_front.pb.txt"
      calibration_file: "calib/camera_front.ini"
    camera_2:
      resize: [1920, 1080]
      config_file: "camera_right.pb.txt"
      calibration_file: "calib/camera_right.ini"
    camera_3:
      resize: [1920, 1080]
      config_file: "camera_left.pb.txt"
      calibration_file: "calib/camera_left.ini"
    camera_4:
      resize: [1920, 1080]
      config_file: "camera_right_front.pb.txt"
      calibration_file: "calib/camera_right_front.ini"
    camera_5:
      resize: [1920, 1080]
      config_file: "camera_left_front.pb.txt"
      calibration_file: "calib/camera_left_front.ini"
    camera_6:
      resize: [1920, 1080]
      config_file: "camera_front_right.pb.txt"
      calibration_file: "calib/camera_front_right.ini"
    camera_7:
      resize: [1920, 1080]
      config_file: "camera_front_left.pb.txt"
      calibration_file: "calib/camera_front_left.ini"
    camera_8:
      resize: [1920, 1080]
      config_file: "camera_front_120.pb.txt"
      calibration_file: "calib/camera_front_120.ini"
      
  radar:
    num: 3
    radar_1:
      config_file: "ars548_front.ini"
      calibration_file: "calib/ars548_front.ini"
    radar_2:
      config_file: "ars548_left_front.ini"
      calibration_file: "calib/ars548_left_front.ini"
    radar_3:
      config_file: "ars548_right_front.ini"
      calibration_file: "calib/ars548_right_front.ini"
            
config_paths:
  sensor_fusion: "sensor_fusion.pb.txt"
  vehicle_dynamics: "vehicle_dynamics.pb.txt"
  control_parameters: "control_parameters.pb.txt"

